// <Trauma>
using Content.Shared._Shitmed.Targeting;
using Content.Shared._Shitmed.Medical.HealthAnalyzer;
// </Trauma>
using Content.Client.UserInterface.Controls;
using Content.Shared.MedicalScanner;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.HealthAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerWindow : FancyWindow
{
    // <Shitmed>
    public event Action<TargetBodyPart?, EntityUid>? OnBodyPartSelected;
    public event Action<HealthAnalyzerMode, EntityUid>? OnModeChanged;
    // </Shitmed>

    public HealthAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
        // <Trauma>
        HealthAnalyzer.OnBodyPartSelected += (part, target) => OnBodyPartSelected?.Invoke(part, target);
        HealthAnalyzer.OnModeChanged += (mode, target) => OnModeChanged?.Invoke(mode, target);
        // </Trauma>
    }

    public void Populate(HealthAnalyzerScannedUserMessage msg)
    {
        HealthAnalyzer.Populate(msg.State);
    }
}
