using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Goobstation.Client.Traitor;

[GenerateTypedNameReferences]
public sealed partial class PenSpinMenu : FancyWindow
{
    public event Action? ResetButtonPressed;
    public event Action<int>? SubmitButtonPressed;

    private int _minDegree;
    private int _maxDegree = 359;
    private string _previousInput = "0";

    public PenSpinMenu()
    {
        RobustXamlLoader.Load(this);

        ResetButton.OnPressed += _ =>
        {
            ResetInput();
            ResetButtonPressed?.Invoke();
        };

        SubmitButton.OnPressed += _ =>
        {
            if (TryGetDegree(out var degree))
            {
                SubmitButtonPressed?.Invoke(degree);
                ResetInput();
            }
        };

        DegreeInput.OnTextChanged += _ =>
        {
            if (string.IsNullOrEmpty(DegreeInput.Text))
                return;

            var filtered = new string(DegreeInput.Text.Where(char.IsDigit).ToArray());
            if (filtered != DegreeInput.Text)
            {
                DegreeInput.Text = filtered;
                return;
            }

            if (int.TryParse(DegreeInput.Text, out var degree))
            {
                if (degree > _maxDegree)
                {
                    DegreeInput.Text = _previousInput;
                    DegreeInput.AddStyleClass("negative");
                }
                else
                {
                    _previousInput = DegreeInput.Text;
                    DegreeInput.RemoveStyleClass("negative");
                }
            }
            else
            {
                DegreeInput.Text = _previousInput;
                DegreeInput.AddStyleClass("negative");
            }
        };

        DegreeInput.OnFocusExit += _ =>
        {
            if (!IsValidDegree(DegreeInput.Text))
            {
                DegreeInput.Text = _previousInput;
                DegreeInput.RemoveStyleClass("negative");
            }
        };

        ResetInput();
    }

    public void SetDegreeRange(int min, int max)
    {
        _minDegree = min;
        _maxDegree = max;
    }

    private void ResetInput()
    {
        DegreeInput.Text = "0";
        _previousInput = "0";
        DegreeInput.RemoveStyleClass("negative");
    }

    private bool TryGetDegree(out int degree)
    {
        degree = 0;
        return int.TryParse(DegreeInput.Text, out degree) && IsValidDegree(degree);
    }

    private bool IsValidDegree(string input)
    {
        return int.TryParse(input, out var degree) && IsValidDegree(degree);
    }

    private bool IsValidDegree(int degree)
    {
        return degree >= _minDegree && degree <= _maxDegree;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }
}
